"""add votes and news

Revision ID: 47a61bb84a8f
Revises: 6b95156e615a
Create Date: 2019-04-20 17:50:39.662620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47a61bb84a8f'
down_revision = '6b95156e615a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'news_id')
    )
    op.add_column('store', sa.Column('disable_vote', sa.Integer(), nullable=False))
    op.add_column('store', sa.Column('enable', sa.Boolean(), nullable=False))
    op.add_column('store', sa.Column('last_ip', sa.String(length=40), nullable=False))
    op.add_column('store', sa.Column('last_modified', sa.DateTime(), nullable=False))
    op.drop_column('store', 'ip')
    op.drop_column('store', 'news')
    op.drop_column('store', 'lastModified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('lastModified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('store', sa.Column('news', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('store', sa.Column('ip', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_column('store', 'last_modified')
    op.drop_column('store', 'last_ip')
    op.drop_column('store', 'enable')
    op.drop_column('store', 'disable_vote')
    op.drop_table('votes')
    op.drop_table('news')
    # ### end Alembic commands ###
