"""add log table

Revision ID: 59a5291c2633
Revises: 248833f75a98
Create Date: 2019-05-05 15:13:56.418481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a5291c2633'
down_revision = '248833f75a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('logger', sa.String(), nullable=True),
                    sa.Column('level', sa.String(), nullable=True),
                    sa.Column('trace', sa.String(), nullable=True),
                    sa.Column('msg', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
