"""Create initial table

Revision ID: 6b95156e615a
Revises: 
Create Date: 2019-04-19 20:56:49.443403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b95156e615a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('news', sa.String(length=128), nullable=False),
    sa.Column('switchable', sa.Boolean(), nullable=False),
    sa.Column('lastModified', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    # ### end Alembic commands ###
