FORMAT: 1A
HOST: https://pts.noob.tw/api/v1

# WhereIsPTS API

WhereIsPTS API is an API allowed user can vote and report the television channel at eat-out restaurants.

# Allowed HTTPs requests:
<pre>
PUT     : To create resource
POST    : Update resource
GET     : Get a resource or list of resources
DELETE  : To delete resource
</pre>

# Description Of Usual Server Responses:
- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found.
- 405 `Method Not Allowed` - requested method is not supported for resource.

---

## Store Collection [/store/{sid}]

+ Parameters
    + sid (required, number) ... serial number of a restaurant

### List a Store [GET]

+ Response 200 (application/json)


        {
            "address": "高雄市鳳山區大明路",
            "last_modified": "2019-05-03T13:45:21.134586+00:00",
            "location": [
                30,
                120
            ],
            "name": "鋼彈販賣店",
            "sid": 500,
            "switchable": true,
            "votes": [
                {
                    "cid": 12,
                    "vote_count": 1
                },
                {
                    "cid": 8,
                    "vote_count": 1
                }
            ]
        }


+ Response 404

+ Response 500

### Modify a Store [PUT]

+ Request (multipart/form-data, boundary=WebKitFormBoundary7MA4YWxkTrZu0gW--)

    + Body


            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="name"
            Content-Type: text/plain

            鋼彈專賣店
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="lat"
            Content-Type: text/plain

            30
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="lng"
            Content-Type: text/plain

            120
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="address"
            Content-Type: text/plain

            高雄市鳳山區大明路
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="switchable"
            Content-Type: text/plain

            true
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--

+ Response 201 (application/json)

    + Headers

            Location:/store/{id}

    + Body

            {
                "address": "高雄市鳳山區大明路",
                "last_modified": "2019-05-05T09:59:06.828556+00:00",
                "location": [
                    30,
                    120
                ],
                "name": "鋼彈專賣店",
                "sid": 8,
                "switchable": true,
                "votes": []
            }

+ Response 404

+ Response 500

### Delete a Store (Voting) [DELETE]

+ Response 204

+ Response 404

+ Response 500

## List Stores [/store/list?{name,lat,lng,radius,page}]

+ Parameters
    + name (optional, String) ... store name
    + lat (required, Number) ... central location of map
    + lng (required, Number) ... central location of map
    + radius (optional, Number, `5`) ... query radius in kilo-meter, maximum is `20`
    + page (optional, Number, `1`) ... page number of pagination

### List Store [GET]

+ Response 201 (application/json)


        {
            "result": [
                {
                    "address": "高雄市鳳山區大明路",
                    "last_modified": "2019-05-05T10:02:25.711448+00:00",
                    "location": [
                        30,
                        120
                    ],
                    "name": "鋼彈專賣店",
                    "sid": 9,
                    "switchable": true,
                    "votes": []
                },
                {
                    "address": "高雄市鳳山區大明路",
                    "last_modified": "2019-05-05T09:59:06.828556+00:00",
                    "location": [
                        30,
                        120
                    ],
                    "name": "鋼彈專賣店",
                    "sid": 8,
                    "switchable": true,
                    "votes": []
                }
            ],
            "total": 2
        }

+ Response 400

+ Response 500

## Add a Store [/store]

add a single restaurant

### Add a Store [POST]

+ Request (multipart/form-data, boundary=WebKitFormBoundary7MA4YWxkTrZu0gW--)

    + Body

            ------WebKitFormBoundary7MA4YWxkTrZu0gW--,
            Content-Disposition: form-data; name="name"
            Content-Type: text/plain

            鋼彈專賣店
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="lat"
            Content-Type: text/plain

            30
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="lng"
            Content-Type: text/plain

            120
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="address"
            Content-Type: text/plain

            高雄市鳳山區大明路
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="switchable"
            Content-Type: text/plain

            true
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--

+ Response 201 (application/json)

        {
            "address": "高雄市鳳山區大明路",
            "last_modified": "2019-05-05T09:59:06.828556+00:00",
            "location": [
                30,
                120
            ],
            "name": "鋼彈專賣店",
            "sid": 8,
            "switchable": true,
            "votes": []
        }

+ Response 400

+ Response 500

## Vote [/vote/store/{sid}]

+ Parameters
    + sid (required, Number) ... restaurant id

### Vote for a wanted channel for a specific restaurant [POST]

+ Request (multipart/form-data, boundary=------WebKitFormBoundary7MA4YWxkTrZu0gW--)

    + Body

            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="cid"
            Content-Type: text/plain

            12
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--

+ Response 201 (application/json)

        {
            "address": "高雄市鳳山區大明路",
            "last_modified": "2019-05-03T13:45:21.134586+00:00",
            "location": [
                30,
                120
            ],
            "name": "鋼彈販賣店",
            "sid": 8,
            "switchable": true,
            "votes": [
                {
                    "cid": 12,
                    "vote_count": 2
                },
                {
                    "cid": 2,
                    "vote_count": 1
                }
            ]
        }

+ Response 400

+ Response 404

+ Response 500

## Channel Collection [/channels]

### Get All Channels [GET]

+ Response 201 (application/json)


        [
            {
                "cid": 2,
                "name": "TVBS新聞"
            },
            {
                "cid": 7,
                "name": "三立新聞"
            },
            {
                "cid": 13,
                "name": "不是新聞"
            },
            {
                "cid": 3,
                "name": "中天新聞"
            },
            {
                "cid": 5,
                "name": "中視新聞"
            },
            {
                "cid": 1,
                "name": "公視新聞"
            },
            {
                "cid": 11,
                "name": "壹電視新聞"
            },
            {
                "cid": 9,
                "name": "年代新聞"
            },
            {
                "cid": 8,
                "name": "東森新聞"
            },
            {
                "cid": 4,
                "name": "民視新聞"
            },
            {
                "cid": 6,
                "name": "華視新聞"
            },
            {
                "cid": 10,
                "name": "非凡新聞"
            },
            {
                "cid": 12,
                "name": "體育新聞"
            }
        ]

+ Response 500

### Add a Channel [POST]

+ Request (multipart/form-data; boundary=------WebKitFormBoundary7MA4YWxkTrZu0gW--)

    + Body

            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="name"
            Content-Type: text/plain

            Fox News
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--

+ Response 201 (application/json)

        {
            "cid": 1,
            "name": "Fox News"
        }

+ Response 500

## Qeury About a Specific Channel [/channel/{cid}]

+ Parameters
    + cid (required, Number) ... channel id

### Search a Specific Channel [GET]

+ Response 201 (application/json)

        {
            "cid": 1,
            "name": "公視新聞"
        }

+ Response 404

+ Response 500

### Modify a Specific Channel [PUT]

+ Request (multipart/form-data; boundary=------WebKitFormBoundary7MA4YWxkTrZu0gW--)

    + Body

            ------WebKitFormBoundary7MA4YWxkTrZu0gW--
            Content-Disposition: form-data; name="name"
            Content-Type: text/plain

            公視新聞
            ------WebKitFormBoundary7MA4YWxkTrZu0gW--

+ Response 201 (application/json)

        {
            "cid": 1,
            "name": "公視新聞"
        }

+ Response 404

+ Response 500
